spring:
  security:
    oauth2client:
      registration:
        google:
          client-id: 366260325335-spab2fbmuguhksr0ggiphkkgmon1bc8k.apps.googleusercontent.com
          client-secret: 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

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  data:
    mongodb:
      uri: ${MONGO_DB_URL}
      database: ${MONGO_DB_NAME}
  cloud:
    azure:
      storage:
        blob:
          account-name: ${AZURE_BLOB_STORAGE_ACCOUNT_NAME}
          account-key: ${AZURE_BLOB_STORAGE_ACCOUNT_KEY}
          endpoint: ${AZURE_BLOB_STORAGE_ENDPOINT}

jwt:
  secret: Xh0LagoOTKRh086LeHLc7zaOVX0Tobd16SRJ5HVp3CI1tUtThD6jLiqMtua6sZMcMBJc7NtW7rLV7Ncd
  access:
    expiration: 43200000
  refresh:
    expiration: 86400000

mongodb:
  collection:
    attribute-definitions: attributeDefinitions
    attribute-values: attributeValues
    products: products
    customers: customers
    contents: contents
    variants: variants
    categories: categories
    medias: medias
    reviews: reviews

server:
  port: 80