spring:
  security:
    oauth2client:
      registration:
        google:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB

  data:
    mongodb:
      uri: ${MONGO_DB_URL}
      database: ${MONGO_DB_NAME}
  cloud:
    azure:
      storage:
        blob:
          account-name: ${AZURE_BLOB_STORAGE_ACCOUNT_NAME}
          account-key: ${AZURE_BLOB_STORAGE_ACCOUNT_KEY}
          endpoint: ${AZURE_BLOB_STORAGE_ENDPOINT}

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: 43200000
  refresh:
    expiration: 86400000

mongodb:
  collection:
    attribute-definitions: attributeDefinitions
    attribute-values: attributeValues
    products: products
    customers: customers
    contents: contents
    variants: variants
    categories: categories
    medias: medias
    reviews: reviews

server:
  port: 80